apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-demo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sagarpatil28dec98/cicd-one-repo.git
    targetRevision: devops
    path: cicd-demo

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

