replicaCount: 2

image:
  repository: sagarpatil98/cicd-demo
  tag: "64"
  pullPolicy: Always

containerPort: 80

service:
  type: NodePort
  port: 80
  targetPort: 80

  ingress:
  enabled: true
  host: cicd-demo.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
